[zh]
  title = "飞飞的博客"
  languageName = "简体中文"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/zh"

[en]
  title = "Fly fly's Blog"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"
