[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 4

[[main]]
  identifier = "archive"
  name = "存档"
  url = "archive"
  weight = 4

[[main]]
  identifier = "gallery"
  name = "作品展示"
  url = "gallery"
  weight = 6
    

[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 4