# Site settings
baseurl = "/"
title = "代码与艺术"
paginate = 5
buildFuture = true

[[menu.social]]
  name = "GitHub"
  title = "fab fa-github-square"
  url = "https://github.com/neoliang"


[[menu.main]]
  name = "存档"
  title = "Archives"
  url = "/archives/"

[[menu.main]]
  name = "作品"
  title = "art"
  url = "/"

[[menu.main]]
  name = "文章"
  title = "posts"
  url = "/posts/"




[params]
  author = "feef"
  twitter = ""
  classes = ["feature-nomusic"]

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
